@Library('jenkins-shared-library') _

pipelineTemplate(
    repo: 'https://github.com/GamatronAI/learnbyexample.git',
    imageName: 'service-a',
    imageTag: 'v1',
    port: '8082',
    region: 'us-east-1',
    accountId: '242201281496',
    ecrRepo: 'service-a'
)
